name: Generate

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Generate
      run: |
        npm install
        npm start
    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.2.1
      with:
        add: ./data/
        default_author: github_actions
